language: node_js
node_js:
  - 10
  - 12
  - 14
cache:
  directories:
    - "node_modules"
env:
  - SUB_PROJECT=ladc
  - SUB_PROJECT=mysql-adapter
  - SUB_PROJECT=mysql2-adapter
  - SUB_PROJECT=pg-adapter
  - SUB_PROJECT=sqlite3-adapter
  - SUB_PROJECT=sql-bricks-modifier
script: cd $SUB_PROJECT && npm i && npm run prepublishOnly
